config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :flats do
    resources :bookings, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat, dependent: :destroy
  validates :start_date, :end_date, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, numericality: { greater_than: 0 }
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: %i[new create]

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    if @booking.save
      redirect_to flat_bookings_path, notice: "your booking is done"
    else
      redirect_to flat_bookings_path, notice: "please choose your dates"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :flat_id)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]
  def index
    @flats = Flat.all
  end

  def show
    # @flat = Flat.find(params[:id])
  end

  def edit
    # @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def update
    # @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    # @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%= simple_form_for [@flat, @booking],
                    html: {
                      data: {
                        controller: 'flatpickr'
                      }
                    } do |f| %>
  <%= f.input :start_date,
              as: :string,
              input_html: {
                data: {
                  flatpickr_target: 'startDateInput',
} } %>
  <%= f.input :end_date,
              as: :string,
              input_html: {
                data: {
                  flatpickr_target: 'endDateInput'
} } %>
  <%= f.submit 'Book now!'%>
<% end %>
<br>
<p><%= link_to "Back to all flats", flats_path %><p>

app/views/flats/edit.html.erb
<%= form_for (@flat) do |f|  %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  <p><%= f.label :address %>
  <%= f.text_field :address %></p>
  <p><%= f.label :description %>
  <%= f.text_field :description %></p>
  <p><%= f.label :price_per_night %>
  <%= f.text_field :price_per_night %></p>
  <p><%= f.label :number_of_guests %>
  <%= f.text_field :number_of_guests %></p>
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<p><% @flats.each do |flat| %>
<li><%= link_to flat.name, flat %></li>
<% end %></p>

<p><%= link_to "Create a flat", new_flat_path %></p>

app/views/flats/new.html.erb
<%= form_for (@flat) do |f|  %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  <p><%= f.label :address %>
  <%= f.text_field :address %></p>
  <p><%= f.label :description %>
  <%= f.text_field :description %></p>
  <p><%= f.label :price_per_night %>
  <%= f.text_field :price_per_night %></p>
  <p><%= f.label :number_of_guests %>
  <%= f.text_field :number_of_guests %></p>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<p>Name: <%= @flat.name %></p>
<p>Address: <%= @flat.address %></p>
<p>Description: <%= @flat.description %></p>
<p>Price: <%= @flat.price_per_night %></p>
<p>Guests: <%= @flat.number_of_guests %></p>


<p><%= link_to "Edit that Flat", edit_flat_path %></p>
<p><%= link_to "Delete that Flat", flat_path(@flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>

<p><%= link_to "Book that Flat", new_flat_booking_path(@flat) %></p>

<h1>All Bookings for the Flat - <%= @flat.name %> </h1>
<p><% @flat.bookings.each do |booking| %></p>
<li>From the <%= booking.start_date%> to <%= booking.end_date%></li>
<% end %>
<br>

<p><%= link_to "Back to all flats", flats_path %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlatsBookingsEsgi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to flats_path, class: "navbar-brand" do %>
      <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZcCRRucTPrfxWZUF9ugDrirl5OJzs-8DDRg&usqp=CAU" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>